import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BookOpen, CheckCircle2, LayoutDashboard, LogOut, PlayCircle, Plus, Users } from "lucide-react";
import "./styles.css";

type Course={id:string;slug:string;title:string;excerpt:string;description?:string;level:string;lesson_count?:number;cover_url?:string;total_lessons?:number;completed_lessons?:number;published?:boolean};
type Session={token:string;user:{id:string;name:string;email:string;role:"member"|"lecturer"|"admin"}};
const api="/api";
const saved=()=>{try{return JSON.parse(localStorage.getItem("akademi-session")||"null") as Session|null}catch{return null}};
async function request(path:string, options:RequestInit={}, session:Session|null=saved()) { const r=await fetch(api+path,{...options,headers:{"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.token}`}:{})}}); const body=await r.json(); if(!r.ok) throw new Error(body.error||"Terjadi kesalahan"); return body; }
function setRobots(value:string){let m=document.querySelector('meta[name="robots"]');if(!m){m=document.createElement("meta");m.setAttribute("name","robots");document.head.append(m)}m.setAttribute("content",value)}
function Button({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button className="button" {...props}>{children}</button>}
function LegacyPublic(){
 const [courses,setCourses]=useState<Course[]>([]);const [detail,setDetail]=useState<Course|null>(null);const [query,setQuery]=useState("");const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{setRobots("index,follow");request("/courses",{},null).then(x=>setCourses(x.courses)).catch(()=>{})},[]);
 const visibleCourses=courses.filter(c=>`${c.title} ${c.excerpt} ${c.level}`.toLowerCase().includes(query.toLowerCase()));
 const features=["Belajar dari praktisi produk", "Materi ringkas dan terstruktur", "Konteks kasus nyata Indonesia", "Ruang tumbuh bersama komunitas"];
 return <main className="home5">
  <header className="home5-header"><a className="home5-logo" href="/">akademi<span>produk</span></a><button className="home5-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Buka menu">☰</button><nav className={menuOpen?"open":""}><a href="#program" onClick={()=>setMenuOpen(false)}>Program</a><a href="#tentang" onClick={()=>setMenuOpen(false)}>Tentang</a><a href="#artikel" onClick={()=>setMenuOpen(false)}>Insight</a><a className="home5-login" href="https://membership.akademiproduk.com">Masuk</a><a className="home5-cta" href="https://membership.akademiproduk.com">Mulai belajar <span>→</span></a></nav></header>
  <section className="home5-hero"><div className="home5-wrap home5-hero-grid"><div className="home5-hero-copy"><div className="home5-rating"><div className="home5-avatars"><i>R</i><i>D</i><i>A</i><i>N</i></div><span><b>4.9</b><em>★★★★★</em><small>oleh para pembelajar</small></span></div><h1>Perjalanan produkmu<br/>dimulai <strong>di sini.</strong></h1><p>Belajar membangun produk digital yang dicintai pengguna—dari strategi, riset, sampai eksekusi.</p><form className="home5-search" onSubmit={e=>{e.preventDefault();document.querySelector("#program")?.scrollIntoView({behavior:"smooth"})}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari program, skill, atau topik"/><button aria-label="Cari">⌕</button></form><div className="home5-hero-actions"><a className="home5-pill" href="#program">Jelajahi program</a><a className="home5-watch" href="#tentang"><b>▶</b> Cara belajarnya</a></div></div><div className="home5-visual"><img src="/home-5/hero-img-3.png" alt="Ilustrasi pembelajar Akademi Produk"/><div className="home5-float home5-float-top"><b>🎓</b><span>Mulai tanpa biaya<small>Program pilihan tersedia</small></span></div><div className="home5-float home5-float-bottom"><b>4.9 ★</b><span>Belajar dengan arah<small><i/><i/><i/></small></span></div></div></div></section>
  <section id="program" className="home5-section"><div className="home5-heading"><span>PROGRAM PILIHAN</span><h2>Temukan jalur belajar yang tepat untukmu.</h2><p>Praktis, relevan, dan dibuat untuk membantumu mengambil langkah berikutnya.</p></div><div className="home5-tabs"><button className="active">Semua program</button><button>Product</button><button>Design</button><button>Marketing</button><button>Business</button></div><div className="home5-course-grid">{visibleCourses.map((c,i)=><article className="home5-course" key={c.id}><div className={'home5-course-image tint-'+i%4}><span>♡</span><div>{c.cover_url?<img src={c.cover_url} alt=""/>:<BookOpen size={48}/>}</div></div><div className="home5-course-body"><h3>{c.title}</h3><p>{c.excerpt}</p><ul><li>▣ {c.lesson_count||c.total_lessons||"—"} lesson</li><li>▥ {c.level}</li><li>★ 4.9</li></ul></div><div className="home5-course-footer"><span><b>AP</b> Akademi Produk</span><button onClick={()=>setDetail(c)}>Lihat program <i>→</i></button></div></article>)}{visibleCourses.length===0&&<p className="home5-empty">Belum ada program yang cocok. Coba kata kunci lain.</p>}</div></section>
  <section className="home5-section home5-instructors"><div className="home5-heading"><span>PARA PRAKTISI</span><h2>Belajar dari orang yang mengerjakannya.</h2><p>Pengajar kami membawa pengalaman nyata dari membangun produk dan bisnis.</p></div><div className="home5-people">{["Strategi produk", "Riset pengguna", "Desain pengalaman", "Pertumbuhan bisnis"].map((role,i)=><article key={role}><div className={'home5-person person-'+i}>{["AP","UX","PM","GR"][i]}</div><b>{role}</b><span>Praktisi Akademi Produk</span></article>)}</div></section>
  <section id="tentang" className="home5-section home5-about"><div><span className="home5-kicker">BELAJAR DENGAN TUJUAN</span><h2>Bukan sekadar menonton materi.</h2><p>Setiap program dirancang untuk membantumu memahami masalah, membuat keputusan yang lebih baik, dan menerapkannya dalam pekerjaan nyata.</p><ul>{features.map(f=><li key={f}>✓ <span>{f}</span></li>)}</ul><a className="home5-solid" href="https://membership.akademiproduk.com">Buat akun <span>→</span></a></div><div className="home5-about-art"><div>✦</div><b>Belajar.<br/>Mencoba.<br/>Bertumbuh.</b><span>Untuk product people Indonesia.</span></div></section>
  <section className="home5-section home5-membership"><div className="home5-heading"><span>MEMBERSHIP</span><h2>Pilih cara belajarmu.</h2><p>Mulai dari program yang sesuai dengan kebutuhanmu hari ini.</p></div><div className="home5-plans">{[["Mulai", "Akses program pilihan", "Untuk mulai mengenal Akademi Produk"],["Bertumbuh", "Akses semua program", "Untuk product people yang ingin berkembang"],["Tim", "Belajar bersama tim", "Untuk organisasi yang ingin bertumbuh bersama"]].map(([name,desc,copy],i)=><article className={i===1?"recommended":""} key={name}><header><span>{i===1?"REKOMENDASI":"MEMBERSHIP"}</span><h3>{name}</h3><b>{desc}</b></header><p>{copy}</p><ul><li>✓ Materi terstruktur</li><li>✓ Progress belajar tersimpan</li><li>✓ Update konten berkala</li></ul><a href="https://membership.akademiproduk.com">Mulai sekarang →</a></article>)}</div></section>
  <section id="artikel" className="home5-section"><div className="home5-heading"><span>INSIGHT & PEMBELAJARAN</span><h2>Catatan untuk membangun produk yang lebih baik.</h2></div><div className="home5-articles">{["Memulai product discovery tanpa kehilangan arah", "Mengubah riset pengguna menjadi keputusan", "Membangun kebiasaan belajar untuk product people"].map((title,i)=><article key={title}><div className={'article-art article-'+i}>✦</div><span>INSIGHT · {i+3} MENIT BACA</span><h3>{title}</h3><p>Perspektif praktis untuk membantu pekerjaan produk sehari-hari.</p><a href="#">Baca selengkapnya →</a></article>)}</div></section>
  <section className="home5-newsletter"><div><h2>Siap tumbuh bersama Akademi Produk?</h2><p>Dapatkan kabar program dan insight pilihan langsung ke emailmu.</p><form onSubmit={e=>e.preventDefault()}><input type="email" required placeholder="Alamat email"/><button>Daftar</button></form></div></section>
  <footer className="home5-footer"><div><a className="home5-logo" href="/">akademi<span>produk</span></a><p>Ruang belajar bagi product people Indonesia.</p></div><div><b>Jelajahi</b><a href="#program">Program</a><a href="#tentang">Tentang</a><a href="#artikel">Insight</a></div><div><b>Butuh bantuan?</b><a href="mailto:halo@akademiproduk.com">halo@akademiproduk.com</a><a href="https://membership.akademiproduk.com">Masuk membership</a></div><small>© 2026 Akademi Produk. Semua hak dilindungi.</small></footer>
  {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><p className="eyebrow">{detail.level}</p><h2>{detail.title}</h2><p>{detail.excerpt}</p><a className="button" href="https://membership.akademiproduk.com">Daftar untuk belajar</a></div></div>}
 </main>}
function Public(){
 const [markup,setMarkup]=useState("");
 useEffect(()=>{
  setRobots("index,follow");
  const styles=["/home-5/assets/css/styles.css","/home-5/assets/css/colors.css","/home-5/assets/css/akademi-header.css"].map(href=>{const link=document.createElement("link");link.rel="stylesheet";link.href=href;link.dataset.home5Template="true";document.head.append(link);return link});
  fetch("/home-5/index.html?v=bb0f77b").then(response=>{if(!response.ok)throw new Error("Template tidak ditemukan");return response.text()}).then(html=>{const template=new DOMParser().parseFromString(html,"text/html");const wrapper=template.querySelector("#main-wrapper");if(!wrapper)throw new Error("Struktur template tidak ditemukan");template.querySelectorAll(".nav-brand").forEach(brand=>{brand.setAttribute("href","/");brand.innerHTML='<span class="ap-brand"><b>akademi</b><strong>produk</strong></span>'});const tutor=template.querySelector(".become-tutor a");if(tutor){tutor.setAttribute("href","https://dashboard58.akademiproduk.com");tutor.innerHTML='<i class="bi bi-person-circle"></i>Menjadi Pengajar'}const signIn=template.querySelector(".join-btn a");if(signIn){signIn.setAttribute("href","https://membership.akademiproduk.com");signIn.removeAttribute("data-bs-toggle");signIn.removeAttribute("data-bs-target");signIn.innerHTML='<i class="bi bi-box-arrow-in-right"></i>Masuk'}document.title="Akademi Produk";setMarkup(wrapper.outerHTML.replaceAll("assets/","/home-5/assets/"))}).catch(()=>setMarkup("<div class=\"home5-template-error\">Template home-5 tidak dapat dimuat.</div>"));
  return()=>styles.forEach(style=>style.remove());
 },[]);
 useEffect(()=>{if(!markup)return;let cancelled=false;const scripts:string[]=["jquery.min.js","popper.min.js","bootstrap.min.js","select2.min.js","slick.js","jquery.counterup.min.js","counterup.min.js","custom.js"];const loaded:HTMLScriptElement[]=[];const load=(name:string)=>new Promise<void>(resolve=>{const script=document.createElement("script");script.src=`/home-5/assets/js/${name}`;script.onload=()=>resolve();script.onerror=()=>resolve();document.body.append(script);loaded.push(script)});(async()=>{for(const script of scripts){if(cancelled)return;await load(script)}})();return()=>{cancelled=true;loaded.forEach(script=>script.remove())};},[markup]);
 return <div className="home5-template" dangerouslySetInnerHTML={{__html:markup}}/>;
}
function Auth({onSession}:{onSession:(s:Session)=>void}){const [login,setLogin]=useState(true),[form,setForm]=useState({name:"",email:"",password:""}),[error,setError]=useState(""); async function submit(e:React.FormEvent){e.preventDefault();setError("");try{const x=await request(login?"/auth/login":"/auth/register",{method:"POST",body:JSON.stringify(form)},null);localStorage.setItem("akademi-session",JSON.stringify(x));onSession(x)}catch(e){setError((e as Error).message)}}return <main className="auth"><a className="brand" href="https://akademiproduk.com">Akademi <b>Produk</b></a><form onSubmit={submit} className="auth-card"><p className="eyebrow">MEMBERSHIP</p><h1>{login?"Selamat datang kembali.":"Mulai perjalananmu."}</h1>{!login&&<label>Nama lengkap<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<p className="error">{error}</p>}<Button type="submit">{login?"Masuk ke membership":"Buat akun"}</Button><button type="button" className="link" onClick={()=>setLogin(!login)}>{login?"Belum punya akun? Daftar":"Sudah punya akun? Masuk"}</button></form></main>}
function Member({session,onLogout}:{session:Session;onLogout:()=>void}){const [courses,setCourses]=useState<Course[]>([]);const [learning,setLearning]=useState<any|null>(null);useEffect(()=>{setRobots("noindex,nofollow,noarchive");request("/member/courses").then(x=>setCourses(x.courses)).catch(()=>{})},[]);async function start(c:Course){try{await request(`/member/courses/${c.id}/enroll`,{method:"POST"});const x=await request(`/member/courses/${c.id}`);setLearning({course:c,lessons:x.lessons})}catch(e){alert((e as Error).message)}}if(learning)return <Learning data={learning} back={()=>setLearning(null)}/>;return <Shell session={session} onLogout={onLogout}><div className="dash-head"><div><p className="eyebrow">MEMBERSHIP</p><h1>Halo, {session.user.name.split(" ")[0]}.</h1><p>Lanjutkan ritme belajarmu hari ini.</p></div><div className="metric"><b>{courses.length}</b><span>Course aktif</span></div></div><section><div className="section-head"><h2>Ruang belajar saya</h2><span>Progress tersimpan otomatis</span></div><div className="course-grid">{courses.map((c,i)=><article className="course member-course" key={c.id}><div className={'course-art art-'+(i%3)}><PlayCircle/><span>{c.level}</span></div><div className="course-copy"><h3>{c.title}</h3><p>{c.excerpt}</p><div className="progress"><i style={{width:`${c.total_lessons?Math.round(100*(Number(c.completed_lessons)||0)/Number(c.total_lessons)):0}%`}}/></div><button onClick={()=>start(c)}>Lanjut belajar <b>→</b></button></div></article>)||<p className="empty">Belum ada course. Buka katalog untuk mulai belajar.</p>}</div></section></Shell>}
function Learning({data,back}:{data:any;back:()=>void}){const [active,setActive]=useState(data.lessons[0]);const [answer,setAnswer]=useState<number|null>(null);async function complete(){await request(`/member/lessons/${active.id}/complete`,{method:"POST"});alert("Lesson ditandai selesai.")}return <main className="learn"><aside><a className="brand" href="#">Akademi <b>Produk</b></a><button className="back" onClick={back}>← Semua course</button><p className="eyebrow">{data.course.title}</p>{data.lessons.map((l:any,i:number)=><button className={active.id===l.id?"lesson active":"lesson"} onClick={()=>{setActive(l);setAnswer(null)}} key={l.id}><span>{String(i+1).padStart(2,"0")}</span>{l.title}</button>)}</aside><article className="lesson-body"><p className="eyebrow">LESSON</p><h1>{active.title}</h1>{active.video_url&&<video controls src={active.video_url}/>}<div className="content">{active.content}</div>{active.quiz_id&&<section className="quiz"><h3>{active.question}</h3>{(active.options as string[]).map((o:string,i:number)=><button className={answer===i?"selected":""} onClick={()=>setAnswer(i)} key={o}>{o}</button>)}<Button disabled={answer===null} onClick={async()=>{const x=await request(`/member/quizzes/${active.quiz_id}/attempt`,{method:"POST",body:JSON.stringify({answerIndex:answer})});alert(x.correct?"Jawaban benar.":"Belum tepat, coba pelajari lagi.")}}>Kirim jawaban</Button></section>}<Button onClick={complete}><CheckCircle2 size={17}/> Tandai selesai</Button></article></main>}
function Shell({session,onLogout,children}:{session:Session;onLogout:()=>void;children:React.ReactNode}){return <main className="dashboard"><aside className="side"><a className="brand" href="#">Akademi <b>Produk</b></a><p className="side-label">MEMBER AREA</p><a className="active"><LayoutDashboard size={18}/> Ringkasan</a><a><BookOpen size={18}/> Course saya</a><div className="side-bottom"><b>{session.user.name}</b><span>{session.user.email}</span><button onClick={onLogout}><LogOut size={16}/> Keluar</button></div></aside><section className="dash-content">{children}</section></main>}
function Staff({session,onLogout}:{session:Session;onLogout:()=>void}){const [courses,setCourses]=useState<Course[]>([]);const [form,setForm]=useState({title:"",excerpt:"",level:"Pemula"});const load=()=>request("/staff/courses").then(x=>setCourses(x.courses));useEffect(()=>{setRobots("noindex,nofollow,noarchive");load().catch(()=>{})},[]);async function add(e:React.FormEvent){e.preventDefault();try{await request("/staff/courses",{method:"POST",body:JSON.stringify({...form,description:form.excerpt,published:false})});setForm({title:"",excerpt:"",level:"Pemula"});load()}catch(e){alert((e as Error).message)}}return <main className="dashboard"><aside className="side"><a className="brand">Akademi <b>Produk</b></a><p className="side-label">OPERATIONS</p><a className="active"><LayoutDashboard size={18}/> Overview</a><a><BookOpen size={18}/> Course builder</a><a><Users size={18}/> Members</a><div className="side-bottom"><b>{session.user.name}</b><span>{session.user.role}</span><button onClick={onLogout}><LogOut size={16}/> Keluar</button></div></aside><section className="dash-content"><div className="dash-head"><div><p className="eyebrow">INTERNAL DASHBOARD</p><h1>Content operations</h1><p>Rancang program, susun lesson, lalu publish saat siap.</p></div><div className="metric"><b>{courses.length}</b><span>Total course</span></div></div><div className="admin-grid"><form className="builder" onSubmit={add}><div className="section-head"><h2>Buat course</h2><Plus size={20}/></div><label>Judul course<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Ringkasan<textarea required value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})}/></label><label>Level<select value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option>Pemula</option><option>Menengah</option><option>Lanjutan</option></select></label><Button type="submit">Simpan draft</Button></form><section className="table-card"><div className="section-head"><h2>Course library</h2><span>{courses.length} item</span></div>{courses.map(c=><div className="row" key={c.id}><div><b>{c.title}</b><span>{c.lesson_count||0} lesson · {c.published?"Published":"Draft"}</span></div><button>Kelola →</button></div>)||<p className="empty">Belum ada course.</p>}</section></div></section></main>}
function App(){const [session,setSession]=useState<Session|null>(saved());const staff=location.hostname.startsWith("dashboard58")||(session?.user.role!=="member"&&location.hostname.includes("localhost")&&location.search.includes("staff"));const logout=()=>{localStorage.removeItem("akademi-session");setSession(null)};if(location.hostname.startsWith("membership")||location.hostname.includes("localhost")&&location.search.includes("member"))return session?<Member session={session} onLogout={logout}/>:<Auth onSession={setSession}/>;if(location.hostname.startsWith("dashboard58")||staff)return session?<Staff session={session} onLogout={logout}/>:<Auth onSession={setSession}/>;return <Public/>}

createRoot(document.getElementById("root")!).render(<App/>);
